In [1]:
# Required: Import packages
import json
import pandas as pd
from PIL import Image
import numpy as np


In [2]:
!pwd

/Users/tiffanyshih/Documents/Coursework/MIDS_207/w207_final_project


# 0. Load and Clean Data

In [3]:
# REQUIRED: Load labels json file containing image object labels

with open('../Final_Project/bdd100k_drivable_labels_trainval/labels/bdd100k_labels_images_train.json') as json_file:
    train_data = json.load(json_file)

with open('../Final_Project/bdd100k_drivable_labels_trainval/labels/bdd100k_labels_images_val.json') as json_file:
    test_data = json.load(json_file)

In [4]:
# REQUIRED: Normalize semi-structured JSON data into a pd dataframe
data_normalized = pd.json_normalize(train_data)
test_data_normalized = pd.json_normalize(test_data)
type(data_normalized)

pandas.core.frame.DataFrame

In [7]:
# Optional - Testing only -- check number of images 
data_normalized.shape

(69863, 6)

In [13]:
# Optional - Testing only -- check format and contents of df
data_normalized.head()

name  timestamp  \
0  0000f77c-6257be58.jpg      10000   
1  0000f77c-62c2a288.jpg      10000   
2  0000f77c-cb820c98.jpg      10000   
3  0001542f-5ce3cf52.jpg      10000   
4  0001542f-7c670be8.jpg      10000   

                                              labels attributes.weather  \
0  [{'category': 'traffic light', 'attributes': {...              clear   
1  [{'category': 'traffic sign', 'attributes': {'...              clear   
2  [{'category': 'car', 'attributes': {'occluded'...              clear   
3  [{'category': 'traffic sign', 'attributes': {'...              clear   
4  [{'category': 'car', 'attributes': {'occluded'...              clear   

  attributes.scene attributes.timeofday  
0      city street              daytime  
1          highway            dawn/dusk  
2      residential            dawn/dusk  
3      city street                night  
4          highway                night

In [14]:
# Optional - Testing only -- check the df values corresponding to a specific image file name
data_normalized[data_normalized['name'] == '0a0a0b1a-7c39d841.jpg']


name  timestamp  \
3915  0a0a0b1a-7c39d841.jpg      10000   

                                                 labels attributes.weather  \
3915  [{'category': 'car', 'attributes': {'occluded'...              clear   

     attributes.scene attributes.timeofday  
3915          highway              daytime

In [ ]:
# Optional - Testing only -- check what format the "labels" contains
type(data_normalized[data_normalized['name'] == '0a0a0b1a-7c39d841.jpg'].labels)
data_normalized.iloc[3915].labels

In [8]:
# Optional - Check size of test and validation data for conditions clear, highway, and daytime.
train_shape = data_normalized[(data_normalized['attributes.weather'] == "clear") & 
               (data_normalized['attributes.scene'] == "highway") & 
               (data_normalized['attributes.timeofday'] == "daytime")].shape

test_shape = test_data_normalized[(test_data_normalized['attributes.weather'] == "clear") & 
               (test_data_normalized['attributes.scene'] == "highway") & 
               (test_data_normalized['attributes.timeofday'] == "daytime")].shape

In [9]:
# Optional - Print out number of images in train and test datasets

print("Train Data: We get a total of %d images taken during clear weather, highway, and daytime." %train_shape[0])
print("Test Data: We get a total of %d images taken during clear weather, highway, and daytime." %test_shape[0])
print("Test data composes of %.2f%% of total dataset" %(100*test_shape[0]/(test_shape[0]+train_shape[0])))

Train Data: We get a total of 3575 images taken during clear weather, highway, and daytime.
Test Data: We get a total of 514 images taken during clear weather, highway, and daytime.
Test data composes of 12.57% of total dataset


# 1. Determine number of objects in the image

In [5]:
# REQUIRED: Function used to clean data, extract labels, and extract data for sunny, 
# highway, and daytime conditions

def clean_data(data_normalized):
    # Initialize lists of object types. Each list will contain 69863 values, each of which corresponds to an image specified as a row in data_cleaned 
    num_objects = []
    num_road = []
    num_sidewalk = []
    num_building = []
    num_wall = []
    num_fence = []
    num_pole = []
    num_traffic_light = []
    num_traffic_sign = []
    num_vegetation = []
    num_terrain = []
    num_sky = []
    num_person = []
    num_rider = []
    num_car = []
    num_truck = []
    num_bus = []
    num_train = []
    num_motorcycle = []
    num_bicycle = []
    num_lanes = []
    num_drivable_area = []

    # Iterate through each image in data_normalized, sum up the number of objects corresponding to each object type, and append to
    # the corresponding object list
    for index, row in data_normalized.iterrows():
        num_objects.append(len(row['labels']))
        num_road.append(sum(x['category'] == 'road' for x in row['labels']))
        num_sidewalk.append(sum(x['category'] == 'sidewalk' for x in row['labels']))
        num_building.append(sum(x['category'] == 'building' for x in row['labels']))
        num_wall.append(sum(x['category'] == 'wall' for x in row['labels']))
        num_fence.append(sum(x['category'] == 'fence' for x in row['labels']))
        num_pole.append(sum(x['category'] == 'pole' for x in row['labels']))
        num_traffic_light.append(sum(x['category'] == 'traffic light' for x in row['labels']))
        num_traffic_sign.append(sum(x['category'] == 'traffic sign' for x in row['labels']))
        num_vegetation.append(sum(x['category'] == 'vegetation' for x in row['labels']))
        num_terrain.append(sum(x['category'] == 'terrain' for x in row['labels']))
        num_sky.append(sum(x['category'] == 'sky' for x in row['labels']))
        num_person.append(sum(x['category'] == 'person' for x in row['labels']))
        num_rider.append(sum(x['category'] == 'rider' for x in row['labels']))
        num_car.append(sum(x['category'] == 'car' for x in row['labels']))
        num_truck.append(sum(x['category'] == 'truck' for x in row['labels']))
        num_bus.append(sum(x['category'] == 'bus' for x in row['labels']))
        num_train.append(sum(x['category'] == 'train' for x in row['labels']))
        num_motorcycle.append(sum(x['category'] == 'motorcycle' for x in row['labels']))
        num_bicycle.append(sum(x['category'] == 'bicycle' for x in row['labels']))
        num_lanes.append(sum(x['category'] == 'lane' for x in row['labels']))
        num_drivable_area.append(sum(x['category'] == 'drivable area' for x in row['labels']))

    data_normalized['num_objects'] = num_objects
    data_normalized['num_sidewalk'] = num_sidewalk
    data_normalized['num_building'] = num_building
    data_normalized['num_wall'] = num_wall
    data_normalized['num_fence'] = num_fence
    data_normalized['num_pole'] = num_pole
    data_normalized['num_traffic_light'] = num_traffic_light
    data_normalized['num_traffic_sign'] = num_traffic_sign
    data_normalized['num_vegetation'] = num_vegetation
    data_normalized['num_terrain'] = num_terrain
    data_normalized['num_sky'] = num_sky
    data_normalized['num_person'] = num_person
    data_normalized['num_rider'] = num_rider
    data_normalized['num_car'] = num_car
    data_normalized['num_truck'] = num_truck
    data_normalized['num_bus'] = num_bus
    data_normalized['num_train'] = num_train
    data_normalized['num_motorcycle'] = num_motorcycle
    data_normalized['num_bicycle'] = num_bicycle
    data_normalized['num_lanes'] = num_lanes
    data_normalized['num_drivable_area'] = num_drivable_area

    # Filter only for images where weather == "clear", scene == "highway", and timeofday == "daytime". 
    # Note: A better implementation may be to filter the dataframe prior to counting the objects per image, 
    # but it may be useful to keep the data_normalized and object counts for each image in case we want to use different filtering values.

    data_cleaned = data_normalized[(data_normalized['attributes.weather'] == "clear") & 
                   (data_normalized['attributes.scene'] == "highway") & 
                   (data_normalized['attributes.timeofday'] == "daytime")]
    return data_cleaned

In [6]:
# Clean Training & Validation Data
training_data_cleaned = clean_data(data_normalized)
training_data_cleaned

name  timestamp  \
10     00067cfb-caba8a02.jpg      10000   
62     002d290d-89f4e5c0.jpg      10000   
88     003baca5-aab2e274.jpg      10000   
89     003baca5-ad660439.jpg      10000   
92     003e23ee-07d32feb.jpg      10000   
...                      ...        ...   
69675  b18cb922-e3af77af.jpg      10000   
69805  fde2db45-f6e2fbd1.jpg      10000   
69809  fde816b0-1b0f1a85.jpg      10000   
69812  fdebe7ab-8409a734.jpg      10000   
69839  fe03fc8a-5dabe7d4.jpg      10000   

                                                  labels attributes.weather  \
10     [{'category': 'traffic light', 'attributes': {...              clear   
62     [{'category': 'car', 'attributes': {'occluded'...              clear   
88     [{'category': 'traffic sign', 'attributes': {'...              clear   
89     [{'category': 'car', 'attributes': {'occluded'...              clear   
92     [{'category': 'traffic sign', 'attributes': {'...              clear   
...                                                  ...                ...   
69675  [{'category': 'traffic sign', 'attributes': {'...              clear   
69805  [{'category': 'car', 'attributes': {'occluded'...              clear   
69809  [{'category': 'traffic sign', 'attributes': {'...              clear   
69812  [{'category': 'car', 'attributes': {'occluded'...              clear   
69839  [{'category': 'traffic sign', 'attributes': {'...              clear   

      attributes.scene attributes.timeofday  num_objects  num_sidewalk  \
10             highway              daytime           29             0   
62             highway              daytime           23             0   
88             highway              daytime            6             0   
89             highway              daytime           15             0   
92             highway              daytime           28             0   
...                ...                  ...          ...           ...   
69675          highway              daytime           18             0   
69805          highway              daytime           11             0   
69809          highway              daytime           29             0   
69812          highway              daytime           40             0   
69839          highway              daytime           25             0   

       num_building  num_wall  ...  num_person  num_rider  num_car  num_truck  \
10                0         0  ...           0          0        3          0   
62                0         0  ...           0          0        6          0   
88                0         0  ...           0          0        2          0   
89                0         0  ...           0          0       10          1   
92                0         0  ...           0          0        6          1   
...             ...       ...  ...         ...        ...      ...        ...   
69675             0         0  ...           0          0        5          0   
69805             0         0  ...           0          0        4          0   
69809             0         0  ...           0          0        8          0   
69812             0         0  ...           0          0       12          0   
69839             0         0  ...           0          0        7          0   

       num_bus  num_train  num_motorcycle  num_bicycle  num_lanes  \
10           1          0               0            0         11   
62           0          1               0            0         10   
88           0          0               0            0          1   
89           0          0               0            0          2   
92           1          0               0            0          8   
...        ...        ...             ...          ...        ...   
69675        0          0               0            0          9   
69805        0          0               0            0          6   
69809        0          0               0            0          9   
69812 

In [7]:
# Clean Test Data
test_data_cleaned = clean_data(test_data_normalized)
test_data_cleaned

name  timestamp  \
13    b1cebfb7-284f5117.jpg      10000   
40    b1d7b3ac-5af8623b.jpg      10000   
55    b1df722f-57d21f3f.jpg      10000   
56    b1df722f-5bcc3db7.jpg      10000   
67    b1e8ad72-c3c79240.jpg      10000   
...                     ...        ...   
9787  c9e7c9d4-18d31194.jpg      10000   
9838  ca077fe9-d2cf4446.jpg      10000   
9858  ca146661-7f70d0c4.jpg      10000   
9897  ca2bcf0e-69e964d2.jpg      10000   
9956  ca55fb23-83a86167.jpg      10000   

                                                 labels attributes.weather  \
13    [{'category': 'car', 'attributes': {'occluded'...              clear   
40    [{'category': 'car', 'attributes': {'occluded'...              clear   
55    [{'category': 'traffic sign', 'attributes': {'...              clear   
56    [{'category': 'car', 'attributes': {'occluded'...              clear   
67    [{'category': 'car', 'attributes': {'occluded'...              clear   
...                                                 ...                ...   
9787  [{'category': 'car', 'attributes': {'occluded'...              clear   
9838  [{'category': 'traffic sign', 'attributes': {'...              clear   
9858  [{'category': 'traffic sign', 'attributes': {'...              clear   
9897  [{'category': 'traffic sign', 'attributes': {'...              clear   
9956  [{'category': 'car', 'attributes': {'occluded'...              clear   

     attributes.scene attributes.timeofday  num_objects  num_sidewalk  \
13            highway              daytime           21             0   
40            highway              daytime           20             0   
55            highway              daytime           25             0   
56            highway              daytime           38             0   
67            highway              daytime           30             0   
...               ...                  ...          ...           ...   
9787          highway              daytime           34             0   
9838          highway              daytime           19             0   
9858          highway              daytime           37             0   
9897          highway              daytime           29             0   
9956          highway              daytime           18             0   

      num_building  num_wall  ...  num_person  num_rider  num_car  num_truck  \
13               0         0  ...           0          0       11          3   
40               0         0  ...           0          0        8          0   
55               0         0  ...           0          0        8          3   
56               0         0  ...           0          4       12          1   
67               0         0  ...           0          0        7          0   
...            ...       ...  ...         ...        ...      ...        ...   
9787             0         0  ...           0          0       19          2   
9838             0         0  ...           0          0        3          0   
9858             0         0  ...           0          0       18          0   
9897             0         0  ...           0          0       13          0   
9956             0         0  ...           4          0        6          0   

      num_bus  num_train  num_motorcycle  num_bicycle  num_lanes  \
13          0          0               0            0          6   
40          1          0               0            0          2   
55          0          0               0            0          9   
56          0          0               0            0          9   
67          0          0               0            0         13   
...       ...        ...             ...          ...        ...   
9787        0          0               0            0          9   
9838        0          0               0            0          6   
9858        0          0               0            0          9   
9897        0          0               0            0          

In [8]:
# Split training dataset to training and validation

training_data_split = training_data_cleaned.sample(frac = 0.9)
val_data_split = training_data_cleaned.drop(training_data_split.index)
val_data_split

name  timestamp  \
95     004071a4-4e8a363a.jpg      10000   
159    006fdb67-f4820206.jpg      10000   
275    00b04b30-501822fa.jpg      10000   
417    011f8481-66729fb4.jpg      10000   
469    013aba02-3fbd03ff.jpg      10000   
...                      ...        ...   
69089  b0253ab0-7f908976.jpg      10000   
69134  b03d18af-a23f2e42.jpg      10000   
69163  b0521762-565e20cd.jpg      10000   
69465  b10af931-d3a3f406.jpg      10000   
69672  b18b7f33-daeaeb20.jpg      10000   

                                                  labels attributes.weather  \
95     [{'category': 'traffic sign', 'attributes': {'...              clear   
159    [{'category': 'bus', 'attributes': {'occluded'...              clear   
275    [{'category': 'car', 'attributes': {'occluded'...              clear   
417    [{'category': 'car', 'attributes': {'occluded'...              clear   
469    [{'category': 'traffic sign', 'attributes': {'...              clear   
...                                                  ...                ...   
69089  [{'category': 'car', 'attributes': {'occluded'...              clear   
69134  [{'category': 'car', 'attributes': {'occluded'...              clear   
69163  [{'category': 'car', 'attributes': {'occluded'...              clear   
69465  [{'category': 'car', 'attributes': {'occluded'...              clear   
69672  [{'category': 'traffic sign', 'attributes': {'...              clear   

      attributes.scene attributes.timeofday  num_objects  num_sidewalk  \
95             highway              daytime           29             0   
159            highway              daytime           40             0   
275            highway              daytime           46             0   
417            highway              daytime           19             0   
469            highway              daytime           30             0   
...                ...                  ...          ...           ...   
69089          highway              daytime           25             0   
69134          highway              daytime           24             0   
69163          highway              daytime           33             0   
69465          highway              daytime           29             0   
69672          highway              daytime           19             0   

       num_building  num_wall  ...  num_person  num_rider  num_car  num_truck  \
95                0         0  ...           0          0       11          0   
159               0         0  ...           5          0        9          0   
275               0         0  ...           0          0       25          0   
417               0         0  ...           0          0       10          0   
469               0         0  ...           0          0       11          2   
...             ...       ...  ...         ...        ...      ...        ...   
69089             0         0  ...           0          0        7          1   
69134             0         0  ...           0          0       10          1   
69163             0         0  ...           0          0       16          0   
69465             0         0  ...           0          0       14          0   
69672             0         0  ...           0          0        3          0   

       num_bus  num_train  num_motorcycle  num_bicycle  num_lanes  \
95           0          0               0            0          8   
159          1          0               0            0          6   
275          0          0               0            0         10   
417          0          0               0            0          6   
469          6          0               0            0          6   
...        ...        ...             ...          ...        ...   
69089        0          0               0            0         10   
69134        0          0               0            0          5   
69163        0          0               0            0          8   
69465 

In [15]:
training_data_split

name  timestamp  \
26905  44ab2984-262d20dd.jpg      10000   
54269  8ac0c658-872dcdfd.jpg      10000   
59980  999d99fa-6bd7c5a8.jpg      10000   
19052  30853278-13d158f8.jpg      10000   
20688  34cbfd92-77b10b17.jpg      10000   
...                      ...        ...   
89     003baca5-ad660439.jpg      10000   
8802   16b0973f-b62dae5e.jpg      10000   
43017  6e1ecbc2-efe66c61.jpg      10000   
52974  87a9cad2-a1655d97.jpg      10000   
66786  aa88fa0c-ca70bfe1.jpg      10000   

                                                  labels attributes.weather  \
26905  [{'category': 'traffic sign', 'attributes': {'...              clear   
54269  [{'category': 'car', 'attributes': {'occluded'...              clear   
59980  [{'category': 'traffic sign', 'attributes': {'...              clear   
19052  [{'category': 'car', 'attributes': {'occluded'...              clear   
20688  [{'category': 'traffic sign', 'attributes': {'...              clear   
...                                                  ...                ...   
89     [{'category': 'car', 'attributes': {'occluded'...              clear   
8802   [{'category': 'car', 'attributes': {'occluded'...              clear   
43017  [{'category': 'traffic light', 'attributes': {...              clear   
52974  [{'category': 'car', 'attributes': {'occluded'...              clear   
66786  [{'category': 'car', 'attributes': {'occluded'...              clear   

      attributes.scene attributes.timeofday  num_objects  num_sidewalk  \
26905          highway              daytime           15             0   
54269          highway              daytime           19             0   
59980          highway              daytime           28             0   
19052          highway              daytime           55             0   
20688          highway              daytime           11             0   
...                ...                  ...          ...           ...   
89             highway              daytime           15             0   
8802           highway              daytime           23             0   
43017          highway              daytime           28             0   
52974          highway              daytime           17             0   
66786          highway              daytime           35             0   

       num_building  num_wall  ...  num_person  num_rider  num_car  num_truck  \
26905             0         0  ...           0          0        3          0   
54269             0         0  ...           0          0        4          0   
59980             0         0  ...           0          0       18          0   
19052             0         0  ...           0          0       44          0   
20688             0         0  ...           0          0        4          1   
...             ...       ...  ...         ...        ...      ...        ...   
89                0         0  ...           0          0       10          1   
8802              0         0  ...           0          0       12          2   
43017             0         0  ...           0          0        7          1   
52974             0         0  ...           0          0       13          0   
66786             0         0  ...           0          0       14          1   

       num_bus  num_train  num_motorcycle  num_bicycle  num_lanes  \
26905        1          0               0            0          6   
54269        0          0               0            0         11   
59980        0          0               0            0          6   
19052        0          0               0            0          4   
20688        0          0               0            0          3   
...        ...        ...             ...          ...        ...   
89           0          0               0            0          2   
8802         0          0               0            0          8   
43017        0          0               0            0          9   
52974 

In [ ]:
# REQUIRED - ONE TIME ONLY - ONLY PERFORM THIS STEP ONCE
# Move training and validation files to a separate folder. 

import os
import shutil

source = '../Final_Project/bdd100k_images_100k/images/100k/train/'
destination = '../Final_Project/bdd100k_images_100k/images/100k/train_clean/'

for f in training_data_split['name']:
    origin = source + f
    dest = destination + f
    shutil.move(origin, dest)


In [12]:
# REQUIRED - ONE TIME ONLY - ONLY PERFORM THIS STEP ONCE
# Move cleaned validation dataset to new folder

source = '../Final_Project/bdd100k_images_100k/images/100k/train/'
destination = '../Final_Project/bdd100k_images_100k/images/100k/val_clean/'

for f in val_data_split['name']:
    origin = source + f
    dest = destination + f
    shutil.move(origin, dest)

In [14]:
# REQUIRED - ONE TIME ONLY - ONLY PERFORM THIS STEP ONCE
# Move cleaned test dataset to new folder

source = '../Final_Project/bdd100k_images_100k/images/100k/val/'
destination = '../Final_Project/bdd100k_images_100k/images/100k/test_clean/'

for f in test_data_cleaned['name']:
    origin = source + f
    dest = destination + f
    shutil.move(origin, dest)
    

In [26]:
# REQUIRED - ONE TIME ONLY - ONLY PERFORM THIS STEP ONCE
# Move masks training files to a separate folder. 

source = '../Final_Project/bdd100k_sem_masks_labels_release/labels/drivable/masks/train/'
destination = '../Final_Project/bdd100k_sem_masks_labels_release/labels/drivable/masks/train_clean/'

for f in training_data_split['name']:
    origin = source + f[:-3] + 'png'
    dest = destination + f[:-3] + 'png'
    shutil.move(origin, dest)

In [29]:
# REQUIRED - ONE TIME ONLY - ONLY PERFORM THIS STEP ONCE
# Move masks validation files to a separate folder. 

source = '../Final_Project/bdd100k_sem_masks_labels_release/labels/drivable/masks/train/'
destination = '../Final_Project/bdd100k_sem_masks_labels_release/labels/drivable/masks/val_clean/'

for f in val_data_split['name']:
    origin = source + f[:-3] + 'png'
    dest = destination + f[:-3] + 'png'
    shutil.move(origin, dest)

In [30]:
# REQUIRED - ONE TIME ONLY - ONLY PERFORM THIS STEP ONCE
# Move masks test files to a separate folder. 

source = '../Final_Project/bdd100k_sem_masks_labels_release/labels/drivable/masks/val/'
destination = '../Final_Project/bdd100k_sem_masks_labels_release/labels/drivable/masks/test_clean/'

for f in test_data_cleaned['name']:
    origin = source + f[:-3] + 'png'
    dest = destination + f[:-3] + 'png'
    shutil.move(origin, dest)

# 2. Set up CNN Model

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.callbacks import TensorBoard
from tensorflow.keras.optimizers import Adam

In [18]:
from warnings import filterwarnings
filterwarnings('ignore')

In [19]:
classifier = Sequential()
classifier.add(Conv2D(32,(3,3),input_shape=(720,1280,3),activation = 'relu'))
classifier.add(MaxPooling2D(pool_size=(2,2),strides=2)) #if stride not given it equal to pool filter size
classifier.add(Conv2D(32,(3,3),activation = 'relu'))
classifier.add(MaxPooling2D(pool_size=(2,2),strides=2))
classifier.add(Flatten())
classifier.add(Dense(units=128,activation='relu'))
classifier.add(Dense(units=1,activation='sigmoid'))
adam = Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False)
classifier.compile(optimizer=adam,loss='binary_crossentropy',metrics=['accuracy'])
#tensorboard = TensorBoard(log_dir="logs/{}".format(time()))

In [20]:
classifier.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 718, 1278, 32)     896       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 359, 639, 32)     0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 357, 637, 32)      9248      
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 178, 318, 32)     0         
 2D)                                                             
                                                                 
 flatten (Flatten)           (None, 1811328)           0         
                                                                 
 dense (Dense)               (None, 128)               2

In [39]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
train_datagen = ImageDataGenerator(rescale=1./255)
val_datagen = ImageDataGenerator(rescale=1./255)
test_datagen = ImageDataGenerator(rescale=1./255)
train_datagen = ImageDataGenerator(rescale=1./255)
val_datagen = ImageDataGenerator(rescale=1./255)
test_datagen = ImageDataGenerator(rescale=1./255)

seed = 1
#Training Set
train_set = train_datagen.flow_from_directory('../Final_Project/bdd100k_sem_masks_labels_release/labels/drivable/masks/train_clean/',
                                             target_size=(720,1280),
                                             batch_size=1,
                                             class_mode='categorical')
mask_generator = mask_datagen.flow_from_directory("dataset/mask/",
                                                   class_mode=None, seed=seed)

#Validation Set
val_set = test_datagen.flow_from_directory('../Final_Project/bdd100k_sem_masks_labels_release/labels/drivable/masks/val_clean/',
                                           target_size=(720,1280),
                                           batch_size = 1,
                                           class_mode='categorical',
                                           shuffle=False)
#Test Set /no output available
test_set = test_datagen.flow_from_directory('../Final_Project/bdd100k_sem_masks_labels_release/labels/drivable/masks/test_clean/',
                                            target_size=(720,1280),
                                            batch_size=1,
                                            shuffle=False)

Found 0 images belonging to 0 classes.
Found 0 images belonging to 0 classes.
Found 0 images belonging to 0 classes.


# 3. Determine the pixel locations of the objects in the image, specifically drivable area

/Users/tiffanyshih/Documents/Coursework/MIDS_207/w207_final_project


# 4. Opening an image file and converting contents to raw pixel values

In [4]:
# Optional: Open sample image and convert to raw pixel values

# with open('../Final_Project/bdd100k/labels/bdd100k_labels_images_train.json') as json_file:

# load the image
with Image.open('../Final_Project/images/10k/train/0a0a0b1a-7c39d841.jpg') as image:
    # convert image to numpy array
    image_data = np.asarray(image)
    
# Print image_data type (np array)
print(type(image_data))

# summarize shape/dimensions (should be height, width, and 
print(image_data.shape)

# Print image data
print(image_data) 

# Convert image data back to a Pillow image
image2 = Image.fromarray(image_data)
print(type(image2))

# summarize image details
print(image2.mode)
print(image2.size)

# Open PIL image 
image2.show()

<class 'numpy.ndarray'>
(720, 1280, 3)
[[[ 55 133 199]
  [ 55 133 199]
  [ 55 133 199]
  ...
  [ 96 178 238]
  [ 95 177 237]
  [ 95 177 237]]

 [[ 55 133 199]
  [ 55 133 199]
  [ 55 133 199]
  ...
  [ 96 178 238]
  [ 95 177 237]
  [ 95 177 237]]

 [[ 56 134 200]
  [ 56 134 200]
  [ 56 134 200]
  ...
  [ 96 178 238]
  [ 95 177 237]
  [ 95 177 237]]

 ...

 [[ 10  34  46]
  [ 10  34  46]
  [ 10  34  46]
  ...
  [  3  14  18]
  [  3  14  18]
  [  3  14  18]]

 [[  7  31  43]
  [  7  31  43]
  [  7  31  43]
  ...
  [  4  15  19]
  [  4  15  19]
  [  4  15  19]]

 [[  8  32  44]
  [  8  32  44]
  [  8  32  44]
  ...
  [  4  15  19]
  [  4  15  19]
  [  4  15  19]]]
<class 'PIL.Image.Image'>
RGB
(1280, 720)


In [37]:
# Optional: Open bitmask image and convert to raw pixel values

# with open('../Final_Project/bdd100k/labels/bdd100k_labels_images_train.json') as json_file:

# load the image
with Image.open('../Final_Project/bdd100k_sem_masks_labels_release/labels/drivable/masks/train_clean/0a0a0b1a-7c39d841.png') as image:
    # convert image to numpy array
    image_data = np.asarray(image)
    
# Print image_data type (np array)
print(type(image_data))

# summarize shape/dimensions (should be height, width, and 
print(image_data.shape)

# Print image data
print(image_data) 

print("mean image data:",np.mean(image_data))
print("min image data:",np.min(image_data))
print("max image data:",np.max(image_data))
print("Unique image data:", np.unique(image_data))
# # Convert image data back to a Pillow image
# image2 = Image.fromarray(image_data)
# print(type(image2))

# # summarize image details
# print(image2.mode)
# print(image2.size)

# # Open PIL image 
# image2.show()

<class 'numpy.ndarray'>
(720, 1280)
[[2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 ...
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]
 [2 2 2 ... 2 2 2]]
mean image data: 1.6110405815972222
min image data: 0
max image data: 2
Unique image data: [0 1 2]


In [ ]:
for filename in data_cleaned['name']:
    # load the image
    filepath = '../Final_Project/images/10k/train/'
    with Image.open(filename + filepath) as image:
        # convert image to numpy array
        image_data = np.asarray(image)

'../Final_Project/images/10k/train/0a0a0b1a-7c39d841.jpg'